[package]
name = "polars-mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# futures = "0.3"
# chrono = "0.4.19"
serde_json = "1.0.81"
serde = "1.0.137"
# tokio = { version = "1", features = ["full"] }
polars-time = "0.21.1"
num = "^0.4"
arrow = { package = "arrow2", git = "https://github.com/jorgecarleitao/arrow2",  default-features = false }
rayon = "1.5.2"
# serde_yaml = "0.8.24"


[dependencies.mongodb]
version = "2.2.1"
default-features = false
features = ["sync"]

[dependencies.polars-core]
version = "0.21.1"
features = ["rows"]

[dependencies.polars]
version = "0.21.1"
git = "https://github.com/universalmind303/polars.git"
rev = "6bd74b9365b99478fe61cc6859a7add30df87416"
features = ["dtype-full", "rows", "lazy"]
