[package]
name = "polars-mongo"
version = "0.1.0"
edition = "2021"
authors = ["universalmind303 <cory.grinstead@gmail.com>"]
license = "MIT"
keywords = ["dataframe", "query-engine", "arrow", "polars", "mongo", "mongodb"]
description = "Connector to read polars dataframes from mongod collections"

[dependencies]
polars-time = "0.21.1"
num = "^0.4"


[dependencies.mongodb]
version = "2.2.1"
default-features = false
features = ["sync"]


[dependencies.polars]
# version = "0.22.2"
git = "https://github.com/universalmind303/polars.git"
rev = "1ae10e90e5173d80309eee48cbee65814da15e86"
features = ["dtype-full", "rows", "lazy"]

[dependencies.polars-core]
# version = "0.22.2"
git = "https://github.com/universalmind303/polars.git"
rev = "1ae10e90e5173d80309eee48cbee65814da15e86"
features = ["rows"]
